### ISSUE TITLE
Stuck at "[E123] Syntax error for Filename....."

### ISSUE THREAD

**Issue by Moerderhoschi** [ScienceDiscoverer/steamscrd#2]
i try to download over 6.800 screenshots of a friend who made a lot screens of me ingame to store that memory on my drive. But again and again i get the same error and i have to manually press space to go over and get the next screenshoot. please fix this so that after 2 sek the program skip and take the next screen.

reproduce with -> steamscrd.exe 76561198024994192 -spage=120

![image](https://github.com/ScienceDiscoverer/steamscrd/assets/163730007/0eeb2310-046b-4bca-9d75-10734d1dc05e)

**Comment by Moerderhoschi** [comment]
wow thank you for your great work. first i tested your program without cookies and now it terminate itself already on page 2.

reproduce with -> steamscrd.exe 76561198024994192 -spage=2

**Comment by ScienceDiscoverer** [comment]
Steam's web design never stops to amaze me..... Take a look at [this screenshot](https://steamcommunity.com/sharedfiles/filedetails/?id=43111690), for example.
Somehow, not even the name of the game can be located there. All the information is just empty...
Obviously this is from Red Orchestra 2 game, but somehow its bugged so much.

Anyway, I just used the default name of `_UNKNOWN_` for all the game that miss name/appid information.
Should be fixed in version `1.0.3`.

**Comment by Moerderhoschi** [comment]
this issue seems fixed now. thank you
