### ISSUE TITLE
Early crash after creating initial folder

### ISSUE THREAD

**Issue by ALegendsTale** [ScienceDiscoverer/steamscrd#3]
Hello, thanks for making this!

I seem to be running into an issue when using both the command line and direct input. After launching steamscrd and inputting a username, it will create a folder for the first game in the queue, then exit.

Any help would be appreciated.

System environment:
Windows 11 (Fresh Install)

**Comment by ScienceDiscoverer** [comment]
Hi! OFC, I'll try to find the problem!
But I will need your username and screenshot page number (or does it crashes on the first page?) to reproduce the bug!
Thanks.

**Comment by ALegendsTale** [comment]
Sure, my username is ALegendsTale. Unfortunately it crashes immediately after creating the first folder (Team Fortress 2 in my case), so I would assume that means the first page.

**Comment by ScienceDiscoverer** [comment]
Hm... Yea, this doesn't look too good. Seems like its local issue, because I can't reproduce it. I downloaded 121+ of your TF2 screenshots, no problems...

To not do a bunch of guesses, I think it would be easier to try and debug it on your machine, if you want.
I made this debug build of the utility and I also included [my custom small debugger](https://github.com/ScienceDiscoverer/npp_msvc_ide/blob/main/sddbg.cpp) in there (so you don't eve need Visual Studio or anything).
[steamscrd_dbg.zip](https://github.com/ScienceDiscoverer/steamscrd/files/15368962/steamscrd_dbg.zip)

Just launch the `launch_sscrd_dbg.cmd` script and try to download the screen. Lets see the exact reason it crashes!
P.S. Antiviruses might have problems with this files, though, if you use any. You can try adding it to exceptions or something like that.

**Comment by ALegendsTale** [comment]
I went ahead and started debugging using your username.

Execution ended with `THREAD DIED IN steamscrd_dbg.exe: 9616 C: 0` and `EXCEPTION_T2I_NON_NUMBER`.
[Full trace](https://pastebin.com/8jfYEysK)

After seeing this I figured maybe it needs the Steam64ID, but that just sends it into a loop retrying to load the first grid page.
`THREAD DIED IN steamscrd_dbg.exe: 4952 C: 0`
`THREAD DIED IN steamscrd_dbg.exe: 4932 C: 0`
`THREAD DIED IN steamscrd_dbg.exe: 2004 C: 0`
`THREAD DIED IN conhost.exe: 7652 C: 0`

Let me know if you need any other information

**Comment by ScienceDiscoverer** [comment]
Well, at least now we have some info... Not enough to pinpoint exactly what happens, though...
The main part of log is this:
```
EXCEPTION_T2I_NON_NUMBER
[TEXT]: [Jan]
CONTINUE EXECUTION:  POSSIBLE
INSTRUCTION ADDRESS: 0x0x00007FFEB105567C
```
This tells that one of my text to integer convertor functions expected number of month in text form, but in some strange way it received `Jan`... The strangest thing is that this is not happening on my machine...

I have a suspicion that somehow your steam webpages have different date-time format in screenshot pages...

Lets try this. I rebuild the debug build and added a little bit of debug logging:
[steamscrd_dbg_with_pdb.zip](https://github.com/ScienceDiscoverer/steamscrd/files/15402268/steamscrd_dbg_with_pdb.zip)
`pdb` file is important to see the line numbers on stack trace (forgot to include it last time). Try to download my screenshots again, and send me the crash trace again, and also `DEBUG.LOG` and `scr_page.html` that should be created in the same directory as `exe` file.

**Comment by ScienceDiscoverer** [comment]
If this is too much trouble, alternatively, can you load [this screenshot](https://steamcommunity.com/sharedfiles/filedetails/?id=121902841), for example, and send me the screenshot of how this part of the page looks on your PC:

![image](https://github.com/ScienceDiscoverer/steamscrd/assets/29157485/6d5ef32b-0db6-4b06-9be9-88a5c2d5303a)

**Comment by ALegendsTale** [comment]
Hi, really sorry for the delay! Here are the requested items:
[Trace](https://pastebin.com/KsSFk5QU)
[scr_page.html](https://pastebin.com/nYCzfNZg)
![image](https://github.com/ScienceDiscoverer/steamscrd/assets/7872628/c964fd9a-9f55-4bbd-b66f-9ffafca0d03e)
The `DEBUG.LOG` wasn't present after running the application.

**Comment by ScienceDiscoverer** [comment]
No problems, I was busy myself, lately...
Yep, the screenshot shows exactly the problem! `Jan 21` instead of `21 Jan`. My code for date translation is pretty dumb, so it only expected `21 Jan` format =)

No wonder there was no `DEBUG.LOG`, as I put it's creation directly below the place where crash occurs!

OK, just uploaded the fix, it should work now! Try release version `[1.0.5](https://github.com/ScienceDiscoverer/steamscrd/releases/tag/v1.0.5)`.

**Comment by ALegendsTale** [comment]
Awesome, I can confirm it works! Thank you for your patience and help :)

**Comment by ScienceDiscoverer** [comment]
I thank you too, for the patience with debugging tasks I handled to you!
