### ISSUE TITLE
Download non-Public screenshots using session cookie

### ISSUE THREAD

**Issue by jschlackman** [ScienceDiscoverer/steamscrd#4]
Would it be possible to use a supplied session cookie to also download screenshots from your own profile that are set to Hidden/Friends Only (rather than just those with Public visibility)?

When logged in to your own account these are available using the same profile URL as public screenshots, but I assume at present that the initial listing is retrieved without passing the session cookie, even when it is supplied at launch.

**Comment by ScienceDiscoverer** [comment]
Your assumption was indeed correct. Somehow I didn't bother to just apply the Login Cookies by default in the very beginning of grid page access. I only used them for the Adult Content downloads in "adult only" games.

Try the [1.0.6 release](https://github.com/ScienceDiscoverer/steamscrd/releases/tag/v1.0.6), I changed it so that the login cookies are applied before the main loop, if present. It seems to be working with Hidden screenshots, I tested it on my profile. Although I have all my screenshots public, so this problem wasn't very important to me personally.

**Comment by jschlackman** [comment]
I do appreciate your fast work on this! Unfortunately it doesn't seem to be working quite right for me - it's still finding only the same total number of screenshots as when I don't provide the session cookie (about 75% of mine aren't public so it's immediately obvious).

My C++ is pretty rusty but I took a quick look at the code and it looks perhaps like the new lines that pass the session cookie are after the first grid page has been loaded, which means the total number of screenshots to download is set based on the public total, not the logged-in total? (Apologies if I'm misunderstanding the order.)

**Comment by ScienceDiscoverer** [comment]
Oh, that was embarrassing situation... It seems that my head wasn't working properly yesterday!
I totally forgot that I get the total grid page amount before the main `for` loop...

I moved the cookies further up, so you can try out the [1.0.7](https://github.com/ScienceDiscoverer/steamscrd/releases/tag/v1.0.7)...
I can't really test it fast enough myself, because it would be kind of long to set entire pages of my screenshots to private =\

**Comment by jschlackman** [comment]
That did the trick, many thanks!

**Comment by Moerderhoschi** [comment]
Hey it's me again. This is a very nice feature but it didn't work on the screenshots of my buddy which has screenshots for friends only. When i visit his Page in Chrome it shows me 107 Arma 3 Screenshots but the tool only downloads the 79 Public. i used the sls & sid parameter but it don't work for me.

steamscrd.exe 76561197971956363 -app=107410 -sls=765... -sid=ccd...
